-- CREATE DATABASE

CREATE DATABASE IF NOT EXISTS infbotutilities;
USE infbotutilities;

-- CREATE TABLES

CREATE TABLE IF NOT EXISTS guilds (
    guildId VARCHAR(32) PRIMARY KEY NOT NULL,
    welcomeChannelId VARCHAR(32) NOT NULL DEFAULT "None",
    boostChannelId VARCHAR(32) NOT NULL DEFAULT "None",
    auditChannelId VARCHAR(32) NOT NULL DEFAULT "None",
);

-- DELETE TABLES

DROP TABLE guilds;

-- DESCRIBE TABLES

DESCRIBE guilds;
