-- CREATE DATABASE

CREATE DATABASE IF NOT EXISTS infbotutilities;
USE infbotutilities;

-- CREATE TABLES

CREATE TABLE IF NOT EXISTS guilds (
    guildId VARCHAR(32) PRIMARY KEY NOT NULL,
    guildOwner VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS guildconfig (
    id INT PRIMARY KEY AUTO_INCREMENT,
    guildId VARCHAR(32) NOT NULL,
    guildLocalPrefix VARCHAR(16) DEFAULT "infu/"
);

-- DELETE TABLES

DROP TABLE guilds;
DROP TABLE guildconfig;

-- DESCRIBE TABLES

DESCRIBE guilds;
DESCRIBE guildconfig;
